version: "3"
networks:
    bipe_network:
        name: bipe_network
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/24
                  gateway: 10.5.0.1
services:
    bipe-web:
        image: "node:alpine"
        container_name: "bipe-web"
        environment:
            - HOST=0.0.0.0
            - PORT=5000
            - CHOKIDAR_USEPOLLING=true
        command: >
            /bin/sh -c "
                cd /root;
                npm install;
                npm start;
            "
        volumes:
            - "./bipe-web/:/root/"
        networks:
            bipe_network:
                ipv4_address: 10.5.0.4
        ports:
            - 5000:5000
    bipe-core-api:
        image: "node:alpine"
        container_name: "bipe-core-api"
        command: >
            /bin/sh -c "
                cd /root;
                npm install;
                npm start;
            "
        volumes:
            - "./bipe-core-api/:/root/"
        networks:
            bipe_network:
                ipv4_address: 10.5.0.3
        ports:
            - 3000:3000
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: bipe
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            bipe_network:
                ipv4_address: 10.5.0.2
        ports:
            - "5432:5432"